### ISSUE TITLE
cannot import name 'pyfeatures' from 'opensfm'

### ISSUE THREAD

**Issue by LukasBommes** [LukasBommes/PV-Hawk#16]
When running PV Hawk for the first time opensfm reconstruction step fails because pyfeatures can not be imported. The issue correpsonds to this issue (https://github.com/mapillary/OpenSfM/issues/545) in OpenSfM.

**Comment by LukasBommes** [comment]
TODO: try if installing libomp via apt in the Docker image fixes the issue.

**Comment by vdebad** [comment]
> TODO: try if installing libomp via apt in the Docker image fixes the issue.

@LukasBommes - I tried the installation of `libomp-dev` via `apt-get` during the custom build by adding it to the `Dockerfile`. It did not solve the problem unfortunately.
