### ISSUE TITLE
run opensfm error

### ISSUE THREAD

**Issue by LingQiu** [LukasBommes/PV-Hawk#31]
hello,
`root@409f85bb78eb:/pvextractor# CUDA_VISIBLE_DEVICES=1 python main.py  storage/pv-hawk-tutorial/workdir/
INFO:__main__:The following tasks will be run: ['opensfm_extract_metadata', 'opensfm_detect_features', 'opensfm_match_features', 'opensfm_create_tracks', 'opensfm_reconstruct', 'triangulate_pv_mod
ules', 'refine_triangulation', 'crop_pv_modules']opensfm_command :  /pvextractor/extractor/mapping/OpenSfM/bin/opensfm extract_metadata "storage/pv-hawk-tutorial/workdir/mapping/cluster_000000" && /pvextractor/extractor/mapping/OpenSfM/bin/opens
fm detect_features "storage/pv-hawk-tutorial/workdir/mapping/cluster_000000" && /pvextractor/extractor/mapping/OpenSfM/bin/opensfm match_features "storage/pv-hawk-tutorial/workdir/mapping/cluster_000000" && /pvextractor/extractor/mapping/OpenSfM/bin/opensfm create_tracks "storage/pv-hawk-tutorial/workdir/mapping/cluster_000000" && /pvextractor/extractor/mapping/OpenSfM/bin/opensfm reconstruct "storage/pv-hawk-tutorial/workdir/mapping/cluster_000000"INFO:__main__:Running OpenSfM reconstruction
/bin/sh: 1: /pvextractor/extractor/mapping/OpenSfM/bin/opensfm: Permission denied
***************************************************************************
Traceback (most recent call last):
  File "main.py", line 164, in <module>
    main(args.workdir)
  File "main.py", line 142, in main
    **settings["triangulate_pv_modules"])
  File "/pvextractor/extractor/mapping/triangulate_modules.py", line 345, in run
    reconstructions = load_reconstructions(mapping_root)
  File "/pvextractor/extractor/mapping/common.py", line 19, in load_reconstructions
    assert len(reconstructions) > 0, "No reconstructions found. Run OpenSfM first."
AssertionError: No reconstructions found. Run OpenSfM first.
`
run opensfm failed, how to do it? Can you give some advice? thx

**Comment by LingQiu** [comment]
solved.

**Comment by LukasBommes** [comment]
Thanks for ponting this out and good you could solve it.
How did you fix it? Just change the permissions for the OpenSfM binary?

**Comment by LingQiu** [comment]
@LukasBommes Yes, just change the permission for the OpenSfM binary.
