### ISSUE TITLE
Convert image coordinates to geographic coordinates

### ISSUE THREAD

**Issue by LingQiu** [LukasBommes/PV-Hawk#32]
How to calculate the geographic coordinates of each pixel in image,which part of the code should I refer to? thx.

**Comment by LukasBommes** [comment]
Hey LingQiu,

at the moment, only the image coordinates of the corners of segmented PV modules are triangulated into the georeference 3D reocnstruction. I.e. only for these points the geocoordinates are known.

However, you could use parts of my code to triangulate arbitrary pixel positions into the 3D reconstructions. Note, that this will only be efficient for a sparse set of points. If you want to estimate the 3D positions of all pixels, then my code would not be suitable for this.

You can find the trinagulation code in [extractor/mapping/triangulate_modules.py](https://github.com/LukasBommes/PV-Hawk/blob/master/extractor/mapping/triangulate_modules.py).

Regards,
Lukas
